"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import Navigation from "../components/navigation";

type LendingItem = { protocol: string; chain: string; market_id: string; reserve_id: string; asset_symbol: string | null; market_name: string | null; supply_apy: number | null; borrow_apy: number | null; utilization: number | null; total_supplied_usd: number | null; total_borrowed_usd: number | null; available_liquidity_usd: number | null; available_liquidity_native: number | null; observed_at: string; source: string; missing_fields: string[]; quality_flags: string[]; opportunity_score: number | null; provisional_opportunity_score: number | null; display_score: number | null; score_confidence: number | null; score_status: string | null; eligible: boolean | null; eligibility_reasons: string[]; economic_relevance: string | null; history_status: Record<string, string>; flags: string[]; };
type Response = { items: LendingItem[]; total: number; limit: number; offset: number };
const API = process.env.NEXT_PUBLIC_API_URL ?? "http://127.0.0.1:8000";
const money = (v: number | null) => v == null ? "N/A" : `$${v.toLocaleString(undefined, { maximumFractionDigits: 0 })}`;
const compactMoney = (v: number | null) => v == null ? "N/A" : v >= 1_000_000 ? `$${(v / 1_000_000).toFixed(1)}M` : v >= 1_000 ? `$${(v / 1_000).toFixed(0)}K` : `$${v.toFixed(0)}`;
const pct = (v: number | null, digits = 2) => v == null ? "N/A" : `${(v * 100).toFixed(digits)}%`;
const score = (v: number | null) => v == null ? "N/A" : v.toFixed(1);
const statusClass = (v: string | null) => (v ?? "na").toLowerCase().replaceAll("_", "-");

export default function LendingPage() {
  const [data, setData] = useState<Response>({ items: [], total: 0, limit: 500, offset: 0 });
  const [asset, setAsset] = useState(""); const [protocol, setProtocol] = useState(""); const [eligibleOnly, setEligibleOnly] = useState(false); const [minScore, setMinScore] = useState("");
  const [sort, setSort] = useState<"score" | "supply" | "apy">("score"); const [error, setError] = useState<string | null>(null); const [updated, setUpdated] = useState<Date | null>(null);
  const load = useCallback(async () => { try { const params = new URLSearchParams({ limit: "500" }); if (asset) params.set("asset", asset); if (protocol) params.set("protocol", protocol); if (eligibleOnly) params.set("eligible_only", "true"); if (minScore) params.set("min_score", minScore); const response = await fetch(`${API}/api/lending?${params}`); if (!response.ok) throw new Error(`Lending API ${response.status}`); setData(await response.json() as Response); setError(null); setUpdated(new Date()); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unknown API error"); } }, [asset, eligibleOnly, minScore, protocol]);
  useEffect(() => { void load(); const timer = setInterval(() => void load(), 30000); return () => clearInterval(timer); }, [load]);
  const items = useMemo(() => [...data.items].sort((a, b) => { const left = sort === "apy" ? a.supply_apy : sort === "supply" ? a.total_supplied_usd : a.display_score; const right = sort === "apy" ? b.supply_apy : sort === "supply" ? b.total_supplied_usd : b.display_score; return (right ?? -1) - (left ?? -1); }), [data.items, sort]);
  const scored = data.items.filter((item) => item.display_score != null); const eligible = data.items.filter((item) => item.eligible === true); const avgSupply = scored.length ? scored.reduce((sum, item) => sum + (item.supply_apy ?? 0), 0) / scored.length : null;
  return <main className="shell platform-shell"><Navigation /><header className="terminal-header"><div><p className="eyebrow brand-mark">D.E.F.I.</p><p className="brand-expansion">DeFi Ecosystem Financial Intelligence</p></div><span className="header-updated">{updated ? `Updated ${updated.toLocaleTimeString()}` : "Connecting..."}</span></header>
    <section className="market-intro"><p className="eyebrow">LENDING OPPORTUNITY INTELLIGENCE</p><h1>Lending markets</h1><p className="subtitle">Supply yield, borrow cost, liquidity and historical evidence.</p><p className="scope"><span className="live-dot" /> Solana · Kamino · Save</p></section>{error && <p className="error">API unavailable: {error}</p>}
    <section className="kpi-row lending-kpis"><div className="terminal-kpi"><span>Reserves tracked</span><strong>{data.total}</strong><small>latest persisted snapshot</small></div><div className="terminal-kpi"><span>Eligible</span><strong>{eligible.length}</strong><small>meets engine criteria</small></div><div className="terminal-kpi"><span>Scored</span><strong>{scored.length}</strong><small>provisional or mature</small></div><div className="terminal-kpi"><span>Avg supply APY</span><strong className="accent-value">{pct(avgSupply, 1)}</strong><small>among scored reserves</small></div></section>
    <section className="card lending-card"><div className="section-heading"><div><h2>Supply &amp; borrow radar</h2><p className="section-note">Read-only view of persisted snapshots and lending evaluations.</p></div><button onClick={() => void load()}>Refresh</button></div><div className="filters"><input aria-label="Asset" placeholder="Search asset" value={asset} onChange={(event) => setAsset(event.target.value)} /><select aria-label="Protocol" value={protocol} onChange={(event) => setProtocol(event.target.value)}><option value="">All protocols</option><option>Kamino</option><option>save</option><option>Drift</option></select><input aria-label="Minimum score" type="number" min="0" max="100" placeholder="Min score" value={minScore} onChange={(event) => setMinScore(event.target.value)} /><label className="toggle"><input type="checkbox" checked={eligibleOnly} onChange={(event) => setEligibleOnly(event.target.checked)} /> Eligible only</label></div>
      <div className="lending-toolbar"><span>Showing {items.length} of {data.total} reserves</span><span className="lending-sort">Sort: <button className={sort === "score" ? "active" : ""} onClick={() => setSort("score")}>Opportunity</button><button className={sort === "apy" ? "active" : ""} onClick={() => setSort("apy")}>Supply APY</button><button className={sort === "supply" ? "active" : ""} onClick={() => setSort("supply")}>Supply</button></span></div>
      <div className="table-wrap lending-table-wrap"><table><thead><tr><th>Asset / market</th><th>Protocol</th><th>Supply APY</th><th>Borrow APY</th><th>Utilization</th><th>Supply</th><th>Available</th><th>Opportunity</th><th>Evidence</th><th>Status</th></tr></thead><tbody>{items.map((item) => <tr key={`${item.protocol}-${item.market_id}-${item.reserve_id}`}><td><Link href={`/lending/${encodeURIComponent(item.reserve_id)}`}><strong>{item.asset_symbol ?? "N/A"}</strong></Link><small className="table-subline">{item.market_name ?? item.market_id}</small></td><td>{item.protocol}</td><td className="numeric apy-value">{pct(item.supply_apy)}</td><td className="numeric">{pct(item.borrow_apy)}</td><td className="numeric">{item.utilization == null ? "N/A" : `${(item.utilization * 100).toFixed(1)}%`}</td><td className="numeric">{compactMoney(item.total_supplied_usd)}</td><td className="numeric">{money(item.available_liquidity_usd)}{item.available_liquidity_usd == null && item.available_liquidity_native != null && <small className="table-subline">{item.available_liquidity_native.toLocaleString()} native</small>}</td><td className="numeric"><b className="score-pill">{score(item.display_score)}</b>{item.opportunity_score == null && item.provisional_opportunity_score != null && <small className="table-subline">provisional</small>}</td><td className="numeric">{item.score_confidence == null ? "N/A" : `${(item.score_confidence * 100).toFixed(0)}%`}</td><td><span className={`status-badge ${statusClass(item.score_status)}`}>{item.score_status ?? "UNSCORED"}</span></td></tr>)}</tbody></table></div>{!error && items.length === 0 && <p className="empty">No persisted lending reserves match these filters.</p>}</section><p className="lending-footnote">APY values use the normalized decimal convention from the engine. Missing utilization/liquidity stays as N/A; it is never inferred in the web layer.</p></main>;
}
