"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import Navigation from "../../components/navigation";

type Detail = { protocol: string; chain: string; asset_symbol: string | null; market_name: string | null; market_id: string; reserve_id: string; supply_apy: number | null; borrow_apy: number | null; utilization: number | null; total_supplied_usd: number | null; total_borrowed_usd: number | null; available_liquidity_usd: number | null; opportunity_score: number | null; provisional_opportunity_score: number | null; display_score: number | null; score_confidence: number | null; score_status: string | null; economic_relevance: string | null; missing_fields: string[]; quality_flags: string[]; flags: string[]; eligibility_reasons: string[]; history_status: Record<string, string>; history: Array<{ observed_at: string; supply_apy: number | null; borrow_apy: number | null; utilization: number | null; total_supplied_usd: number | null; }> };
const API = process.env.NEXT_PUBLIC_API_URL ?? "http://127.0.0.1:8000";
const pct = (v: number | null) => v == null ? "N/A" : `${(v * 100).toFixed(2)}%`;
const money = (v: number | null) => v == null ? "N/A" : `$${v.toLocaleString(undefined, { maximumFractionDigits: 0 })}`;

export default function LendingDetailPage() {
  const params = useParams<{ reserve_id: string }>(); const [data, setData] = useState<Detail | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { fetch(`${API}/api/lending/${encodeURIComponent(params.reserve_id)}`).then(async (response) => { if (!response.ok) throw new Error(`Lending API ${response.status}`); return response.json(); }).then(setData).catch((reason) => setError(reason instanceof Error ? reason.message : "Unknown API error")); }, [params.reserve_id]);
  return <main className="shell platform-shell"><Navigation /><Link className="back" href="/lending">← Back to lending markets</Link>{error && <p className="error">{error}</p>}{data && <><p className="eyebrow">LENDING RESERVE</p><h1>{data.asset_symbol ?? "N/A"}</h1><p className="subtitle">{data.protocol} · {data.market_name ?? data.market_id}</p><section className="detail-grid lending-detail-grid"><div><span>Supply APY</span><strong>{pct(data.supply_apy)}</strong></div><div><span>Borrow APY</span><strong>{pct(data.borrow_apy)}</strong></div><div><span>Utilization</span><strong>{pct(data.utilization)}</strong></div><div><span>Total supplied</span><strong>{money(data.total_supplied_usd)}</strong></div><div><span>Total borrowed</span><strong>{money(data.total_borrowed_usd)}</strong></div><div><span>Opportunity</span><strong>{data.display_score == null ? "N/A" : data.display_score.toFixed(1)}</strong></div><div><span>Confidence</span><strong>{data.score_confidence == null ? "N/A" : `${(data.score_confidence * 100).toFixed(0)}%`}</strong></div><div><span>Evaluation</span><strong>{data.score_status ?? "UNSCORED"}</strong></div></section><section className="card detail-section"><h2>Historical APY evidence</h2><p className="section-note">24h: {data.history_status["24h"] ?? "N/A"} · 7d: {data.history_status["7d"] ?? "N/A"} · 30d: {data.history_status["30d"] ?? "N/A"}</p><div className="history-table-wrap"><table><thead><tr><th>Observed</th><th>Supply APY</th><th>Borrow APY</th><th>Utilization</th><th>Supply</th></tr></thead><tbody>{data.history.slice(-50).reverse().map((row) => <tr key={row.observed_at}><td>{new Date(row.observed_at).toLocaleString()}</td><td>{pct(row.supply_apy)}</td><td>{pct(row.borrow_apy)}</td><td>{pct(row.utilization)}</td><td>{money(row.total_supplied_usd)}</td></tr>)}</tbody></table></div></section><section className="card detail-section"><h2>Data quality</h2><p className="section-note">Missing: {data.missing_fields.length ? data.missing_fields.join(", ") : "none"}</p><p className="section-note">Flags: {data.flags.length ? data.flags.join(", ") : "none"}{data.quality_flags.length ? ` · source: ${data.quality_flags.join(", ")}` : ""}</p></section></>}</main>;
}
