"use client";

import Link from "next/link";
import { use, useEffect, useMemo, useState } from "react";

type Pool = { pair: string; protocol: string | null; pool_address: string | null; type: string | null; fee_tier: number | null; opportunity_score?: number | null; risk_coverage?: number | null; asset_risk?: number | null; volatility_risk?: number | null; structure_risk?: number | null; apr?: number | null; tvl_usd?: number | null; volume_tvl_ratio?: number | null; status?: string | null; trend?: string | null; snapshot_time?: string | null; current_eligibility?: "ELIGIBLE" | "EXCLUDED" | "UNKNOWN"; eligibility_reason?: string | null; risk_modules?: { asset: boolean; volatility: boolean; structure: boolean }; risk_modules_available?: number; history?: Array<Record<string, unknown>>; };
type HistoryTab = "fee" | "opportunity" | "tvl";
const API = process.env.NEXT_PUBLIC_API_URL ?? "http://127.0.0.1:8000";
const visualPair = (pair: string) => pair.replace(/\bWSOL\b/gi, "SOL");
const samePair = (left: string, right: string) => visualPair(left).replace(/\s+/g, "").toUpperCase() === visualPair(right).replace(/\s+/g, "").toUpperCase();
const value = (item: unknown) => item === null || item === undefined || item === "" ? "N/A" : String(item);
const numberValue = (item: unknown, digits = 1) => typeof item === "number" ? item.toFixed(digits) : "N/A";
const money = (item: unknown) => typeof item === "number" ? `$${item.toLocaleString(undefined, { maximumFractionDigits: 0 })}` : "N/A";
const ageSeconds = (timestamp: string | null | undefined) => timestamp ? Math.max(0, (Date.now() - Date.parse(timestamp)) / 1000) : Infinity;
const age = (timestamp: string | null | undefined) => { const seconds = ageSeconds(timestamp); if (!Number.isFinite(seconds)) return "N/A"; if (seconds < 60) return `${Math.floor(seconds)}s`; if (seconds < 3600) return `${Math.floor(seconds / 60)}m`; return `${Math.floor(seconds / 3600)}h`; };
const historyMetric = (item: Record<string, unknown>, tab: HistoryTab) => tab === "fee" ? item.calculated_fee_apr : tab === "opportunity" ? item.opportunity_score : item.tvl_usd;
const chartPath = (history: Array<Record<string, unknown>>, tab: HistoryTab) => { const values = history.map((item) => historyMetric(item, tab)).filter((item): item is number => typeof item === "number"); if (values.length < 2) return null; const min = Math.min(...values); const span = Math.max(...values) - min || 1; return history.map((item, index) => { const metric = historyMetric(item, tab); if (typeof metric !== "number") return null; const x = index / (history.length - 1) * 780 + 10; const y = 200 - ((metric - min) / span * 180 + 10); return `${x.toFixed(1)},${y.toFixed(1)}`; }).filter(Boolean).join(" "); };
const dappUrl = (protocol: string | null) => protocol === "Raydium" ? "https://raydium.io" : protocol === "Orca" ? "https://www.orca.so" : protocol === "Meteora" ? "https://app.meteora.ag" : null;

export default function ComparePage({ params }: { params: Promise<{ pair: string }> }) {
  const { pair: encodedPair } = use(params); const targetPair = decodeURIComponent(encodedPair).replaceAll("-", " / ");
  const [pools, setPools] = useState<Pool[]>([]); const [error, setError] = useState<string | null>(null); const [includeHistory, setIncludeHistory] = useState(false); const [historyTab, setHistoryTab] = useState<HistoryTab>("fee");
  useEffect(() => { fetch(`${API}/api/pools?limit=500`).then((response) => { if (!response.ok) throw new Error(`API ${response.status}`); return response.json(); }).then(async (payload: { items: Pool[] }) => { const matches = payload.items.filter((item) => samePair(item.pair, targetPair)); setPools(await Promise.all(matches.map(async (item) => { if (!item.pool_address) return item; const response = await fetch(`${API}/api/pools/${encodeURIComponent(item.pool_address)}`); return response.ok ? await response.json() as Pool : item; }))); }).catch((reason: Error) => setError(reason.message)); }, [targetPair]);
  const current = useMemo(() => pools.filter((pool) => pool.current_eligibility === "ELIGIBLE" && ageSeconds(pool.snapshot_time) <= 30 * 60), [pools]);
  const visible = includeHistory ? pools : current;
  const leaders = useMemo(() => { const best = (label: string, getter: (pool: Pool) => number | null | undefined, lower = false) => { if (!current.length) return null; const available = current.filter((pool) => typeof getter(pool) === "number"); if (!available.length) return null; const winner = available.reduce((a, b) => lower ? (getter(b)! < getter(a)! ? b : a) : (getter(b)! > getter(a)! ? b : a)); return `${label}: ${winner.protocol ?? "N/A"} (${numberValue(getter(winner), 2)})`; }; return [best("Highest Opportunity", (pool) => pool.opportunity_score), best("Highest Fee APR", (pool) => pool.apr), best("Highest TVL", (pool) => pool.tvl_usd), best("Highest Volume/TVL", (pool) => pool.volume_tvl_ratio)].filter((item): item is string => Boolean(item)); }, [current]);
  const historical = pools.filter((pool) => !current.includes(pool));
  return <main className="shell"><Link className="back" href="/">&lt;- Back to radar</Link><header><p className="eyebrow">PAIR COMPARE</p><h1>{visualPair(targetPair)}</h1><p className="subtitle">Cross-protocol pool comparison</p><div className="external-actions">{visible.map((pool) => pool.pool_address && <span key={pool.pool_address}><a href={`https://solscan.io/account/${encodeURIComponent(pool.pool_address)}`} target="_blank" rel="noreferrer">{pool.protocol} Explorer</a>{dappUrl(pool.protocol) && <a href={dappUrl(pool.protocol)!} target="_blank" rel="noreferrer">DApp</a>}</span>)}</div></header>{error && <p className="error">API unavailable: {error}</p>}{!error && <label className="compare-filter"><input type="checkbox" checked={includeHistory} onChange={(event) => setIncludeHistory(event.target.checked)} /> Include stale/history</label>}{!error && !visible.length && <p className="empty">No current eligible pools found for this pair.</p>}{visible.length > 0 && <>
    <section className="detail-section"><h2>{includeHistory ? "All known pools" : "Current pools"}</h2><div className="card compare-wrap"><table className="compare-table"><thead><tr><th>Metric</th>{visible.map((pool) => <th key={pool.pool_address}>{pool.protocol} · <Link href={`/pools/${encodeURIComponent(pool.pool_address ?? "")}`}>{value(pool.type)}</Link></th>)}</tr></thead><tbody>{[["Protocol", (p: Pool) => value(p.protocol)], ["Pool type", (p: Pool) => value(p.type)], ["Fee tier", (p: Pool) => typeof p.fee_tier === "number" ? `${(p.fee_tier * 100).toFixed(2)}%` : "N/A"], ["Eligibility", (p: Pool) => p.current_eligibility ?? "UNKNOWN"], ["Opportunity", (p: Pool) => numberValue(p.opportunity_score)], ["Fee APR", (p: Pool) => typeof p.apr === "number" ? `${p.apr.toFixed(2)}%` : "N/A"], ["TVL", (p: Pool) => money(p.tvl_usd)], ["Volume/TVL", (p: Pool) => typeof p.volume_tvl_ratio === "number" ? `${p.volume_tvl_ratio.toFixed(2)}x` : "N/A"], ["Asset Risk", (p: Pool) => numberValue(p.asset_risk)], ["Volatility Risk", (p: Pool) => numberValue(p.volatility_risk)], ["Structure Risk", (p: Pool) => numberValue(p.structure_risk)], ["Risk Data", (p: Pool) => `${p.risk_modules_available ?? 0} / 3`], ["Status", (p: Pool) => value(p.status)], ["Trend", (p: Pool) => value(p.trend)], ["Snapshot age", (p: Pool) => age(p.snapshot_time)]].map(([label, getter]) => <tr key={label as string}><th>{label as string}</th>{visible.map((pool) => <td key={`${pool.pool_address}-${label}`}>{(getter as (pool: Pool) => string)(pool)}</td>)}</tr>)}</tbody></table></div></section>
    <section className="detail-section"><h2>Current leaders</h2><div className="card difference-list">{leaders.length ? leaders.map((item) => <p key={item}>{item}</p>) : <p>No current eligible pool has comparable data.</p>}</div></section>
    {historical.length > 0 && <section className="detail-section"><h2>Historical / non-current observations</h2><div className="card difference-list">{historical.map((pool) => <p key={pool.pool_address}>{pool.protocol} {visualPair(pool.pair)} previously showed OPP {numberValue(pool.opportunity_score, 2)} / APR {typeof pool.apr === "number" ? `${pool.apr.toFixed(2)}%` : "N/A"} · Snapshot age: {age(pool.snapshot_time)} · Eligibility: {pool.current_eligibility ?? "UNKNOWN"}</p>)}</div></section>}
    <section className="detail-section"><h2>History</h2><div className="card compare-history"><div className="history-tabs">{([['fee', 'Fee APR history'], ['opportunity', 'Opportunity history'], ['tvl', 'TVL history']] as [HistoryTab, string][]).map(([key, label]) => <button className={historyTab === key ? "tab active" : "tab"} onClick={() => setHistoryTab(key)} key={key}>{label}</button>)}</div><svg className="history-chart" viewBox="0 0 800 220">{visible.map((pool, index) => <polyline key={pool.pool_address} fill="none" stroke={`hsl(${165 + index * 45} 70% 65%)`} strokeWidth="3" points={chartPath(pool.history ?? [], historyTab) ?? ""} />)}</svg><div className="legend">{visible.map((pool, index) => <span key={pool.pool_address}><i style={{ background: `hsl(${165 + index * 45} 70% 65%)` }} />{pool.protocol} · {pool.current_eligibility === "ELIGIBLE" ? "CURRENT" : "STALE / NON-CURRENT"}</span>)}</div><p className="section-note">Only real persisted snapshots are shown; each line ends at its last available observation.</p></div></section>
  </>}</main>;
}
